config/routes.rb
PostingsSimple::Engine.routes.draw do
  get "home/index"

  resources :postings


end

app/models/postings_simple/posting.rb
module PostingsSimple
  class Posting < ActiveRecord::Base
    attr_accessible :name
  end
end

app/controllers/postings_simple/application_controller.rb
module PostingsSimple
  class ApplicationController < ActionController::Base
  end
end

app/controllers/postings_simple/home_controller.rb
require_dependency "postings_simple/application_controller"

module PostingsSimple
  class HomeController < ApplicationController
    def index
    end
  end
end

app/controllers/postings_simple/postings_controller.rb
require_dependency "postings_simple/application_controller"

module PostingsSimple
  class PostingsController < ApplicationController
    # GET /postings
    # GET /postings.json
    def index
      @postings = Posting.all

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @postings }
      end
    end

    # GET /postings/1
    # GET /postings/1.json
    def show
      @posting = Posting.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @posting }
      end
    end

    # GET /postings/new
    # GET /postings/new.json
    def new
      @posting = Posting.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @posting }
      end
    end

    # GET /postings/1/edit
    def edit
      @posting = Posting.find(params[:id])
    end

    # POST /postings
    # POST /postings.json
    def create
      @posting = Posting.new(params[:posting])

      respond_to do |format|
        if @posting.save
          format.html { redirect_to @posting, notice: 'Posting was successfully created.' }
          format.json { render json: @posting, status: :created, location: @posting }
        else
          format.html { render action: "new" }
          format.json { render json: @posting.errors, status: :unprocessable_entity }
        end
      end
    end

    # PUT /postings/1
    # PUT /postings/1.json
    def update
      @posting = Posting.find(params[:id])

      respond_to do |format|
        if @posting.update_attributes(params[:posting])
          format.html { redirect_to @posting, notice: 'Posting was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @posting.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /postings/1
    # DELETE /postings/1.json
    def destroy
      @posting = Posting.find(params[:id])
      @posting.destroy

      respond_to do |format|
        format.html { redirect_to postings_url }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/postings_simple/application_helper.rb
module PostingsSimple
  module ApplicationHelper
  end
end

app/helpers/postings_simple/home_helper.rb
module PostingsSimple
  module HomeHelper
  end
end

app/helpers/postings_simple/postings_helper.rb
module PostingsSimple
  module PostingsHelper
  end
end

app/views/layouts/postings_simple/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PostingsSimple</title>
  <%= stylesheet_link_tag    "postings_simple/application", :media => "all" %>
  <%= javascript_include_tag "postings_simple/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/postings_simple/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/postings_simple/home/index.html.erb</p>

app/views/postings_simple/postings/_form.html.erb
<%= form_for(@posting) do |f| %>
  <% if @posting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@posting.errors.count, "error") %> prohibited this posting from being saved:</h2>

      <ul>
      <% @posting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/postings_simple/postings/edit.html.erb
<h1>Editing posting</h1>

<%= render 'form' %>

<%= link_to 'Show', @posting %> |
<%= link_to 'Back', postings_path %>

app/views/postings_simple/postings/index.html.erb
<h1>Listing postings</h1>
<%= current_user %>
<%= user_signed_in? %>
<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @postings.each do |posting| %>
  <tr>
    <td><%= posting.name %></td>
    <td><%= link_to 'Show', posting %></td>
    <td><%= link_to 'Edit', edit_posting_path(posting) %></td>
    <td><%= link_to 'Destroy', posting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Posting', new_posting_path %>

app/views/postings_simple/postings/new.html.erb
<h1>New posting</h1>

<%= render 'form' %>

<%= link_to 'Back', postings_path %>

app/views/postings_simple/postings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @posting.name %>
</p>


<%= link_to 'Edit', edit_posting_path(@posting) %> |
<%= link_to 'Back', postings_path %>